// AUTO-GENERATED by scripts/sync-model-catalog.mjs
// Do not edit manually; update model-catalog.json and rerun the script.
export const defaultModel = "gemini-flash" as const;
export const supportedModels = [
  "gemini-flash",
  "gemini-2.5-flash",
  "gemini-2.5-flash-lite",
  "gemini-2.5-pro",
  "gemini-3-flash-preview",
  "gemini-3.1-pro-preview"
] as const;
